oro_entity_config:
    security:
        entity:
            items:
                type:
                    options:
                        auditable: false
                permissions: ~
                group_name: ~

                # This attribute determines within which group an object can be shared. For example,
                # if share_scope=[organization] than user can share the object only to organizations.
                # Role permission "Share" says who can share, "Share Scope" says how object can be shared.
                share_scopes:
                    options:
                        priority: 250
                        default_value: ['user']
                    form:
                        type: choice
                        options:
                            block: associations
                            required: false
                            multiple: true
                            expanded: true
                            label: 'oro.security.share_scopes.label'
                            choices:
                                'global': 'oro.security.share_scopes.global'
                                'organization': 'oro.security.share_scopes.organization'
                                'division': 'oro.security.share_scopes.division'
                                'business_unit': 'oro.security.share_scopes.business_unit'
                                'user': 'oro.security.share_scopes.user'
