oro_entity_config:
    security:
        entity:
            items:
                type:
                    options:
                        auditable: false
                        internal: true
                permissions: ~
                group_name: ~
