permissions:
    PERMISSION1:
        label: Label for Permission 1
        group_names: frontend
        apply_to_all: true
        apply_to_entities:
            - OroB2B\Bundle\SaleBundle\Entity\Quote
            - OroB2B\Bundle\OrderBundle\Entity\Order
        exclude_entities:
            - OroB2B\Bundle\SaleBundle\Entity\QuoteProduct
            - OroB2B\Bundle\OrderBundle\Entity\OrderLineItem

#    PERMISSION2:
#        label: Label for Permission 2
#        description: Permission 2 description
#        group_names: ['', 'frontend']
#        apply_to_all: false
#        apply_to_entities:
#            - entity2
#            - entity3
#        exclude_entities:
#            - entity11
#            - entity12
#
#    PERMISSION3:
#        label: Label for Permission 3
#        apply_to_all: false
#        apply_to_entities:
#            - entity3
#            - entity4
#        exclude_entities:
#            - entity12
#            - entity13
#
#    PERMISSION4:
#        label: Label for Permission 4
#        apply_to_all: true
