permissions:
    PERMISSION1:
        label: Label for Permission 1
        group_names: frontend
        apply_to_all: true
        apply_to_entities:
            - OroB2B\Bundle\SaleBundle\Entity\Quote
            - OroB2B\Bundle\OrderBundle\Entity\Order
        exclude_entities:
            - OroB2B\Bundle\SaleBundle\Entity\QuoteProduct
            - OroB2B\Bundle\OrderBundle\Entity\OrderLineItem

    PERMISSION2:
        label: Label for Permission 2
        description: Permission 2 description
        group_names: ['', 'frontend']
        apply_to_all: false
        apply_to_entities:
            - OroB2B\Bundle\OrderBundle\Entity\Order
            - OroB2B\Bundle\RFPBundle\Entity\Request
        exclude_entities:
            - OroB2B\Bundle\OrderBundle\Entity\OrderLineItem
            - OroB2B\Bundle\RFPBundle\Entity\RequestProductItem

    PERMISSION3:
        label: Label for Permission 3
        apply_to_all: false
        apply_to_entities:
            - OroB2B\Bundle\RFPBundle\Entity\Request
            - OroB2B\Bundle\ProductBundle\Entity\Product
        exclude_entities:
            - OroB2B\Bundle\RFPBundle\Entity\RequestProductItem
            - OroB2B\Bundle\ProductBundle\Entity\ProductUnit

    PERMISSION4:
        label: Label for Permission 4
        apply_to_all: true
