parameters:
    # replace the default ACL provider with an extended version of the provider
    security.acl.dbal.provider.class:                          Oro\Bundle\SecurityBundle\Acl\Dbal\MutableAclProvider

    oro_security.acl.manager.class:                            Oro\Bundle\SecurityBundle\Acl\Persistence\AclManager
    oro_security.acl.cache.class:                              Oro\Bundle\SecurityBundle\Acl\Cache\FilesystemCache
    oro_security.acl.ace_provider.class:                       Oro\Bundle\SecurityBundle\Acl\Persistence\AceManipulationHelper
    oro_security.acl.privilege_repository.class:               Oro\Bundle\SecurityBundle\Acl\Persistence\AclPrivilegeRepository
    oro_security.acl.extension_selector.class:                 Oro\Bundle\SecurityBundle\Acl\Extension\AclExtensionSelector
    oro_security.acl.extension.entity.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\EntityAclExtension
    oro_security.acl.extension.action.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\ActionAclExtension
    oro_security.acl.voter.class:                              Oro\Bundle\SecurityBundle\Acl\Voter\AclVoter
    oro_security.acl.provider.class:                           Oro\Bundle\SecurityBundle\Acl\Domain\RootBasedAclProvider
    oro_security.acl.permission_granting_strategy.class:       Oro\Bundle\SecurityBundle\Acl\Domain\PermissionGrantingStrategy
    oro_security.acl.permission_map.class:                     Oro\Bundle\SecurityBundle\Acl\Permission\PermissionMap
    oro_security.acl.object_identity_factory.class:            Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityFactory
    oro_security.acl.object_identity_retrieval_strategy.class: Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityRetrievalStrategy
    oro_security.acl.object_id_accessor.class:                 Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdAccessor

    oro_security.owner.tree.class:                             Oro\Bundle\SecurityBundle\Owner\OwnerTree
    oro_security.owner.decision_maker.class:                   Oro\Bundle\SecurityBundle\Owner\EntityOwnershipDecisionMaker
    oro_security.orm.ownership_sql_filter.class:               Oro\Bundle\SecurityBundle\ORM\SqlFilter\OwnershipFilter
    oro_security.orm.ownership_sql_filter_builder.class:       Oro\Bundle\SecurityBundle\ORM\SqlFilter\OwnershipFilterBuilder

    oro_security.type.oro_acl_entity_row.class:                Oro\Bundle\SecurityBundle\Form\Type\EntityRowType
    oro_security.type.oro_acl_collection.class:                Oro\Bundle\SecurityBundle\Form\Type\CollectionType
    oro_security.type.oro_acl_object_name.class:               Oro\Bundle\SecurityBundle\Form\Type\ObjectNameType
    oro_security.type.oro_acl_label.class:                     Oro\Bundle\SecurityBundle\Form\Type\ObjectLabelType

    oro_security.entity_security_metadata_provider.class:      Oro\Bundle\SecurityBundle\Metadata\EntitySecurityMetadataProvider
    oro_security.entity_security_metadata_provider.cache.class: Doctrine\Common\Cache\FilesystemCache
    oro_security.action_metadata_provider.class:               Oro\Bundle\SecurityBundle\Metadata\ActionMetadataProvider

    oro_security.acl.annotation_provider.class:               Oro\Bundle\SecurityBundle\Metadata\AclAnnotationProvider
    oro_security.acl.annotation_provider.cache.class:         Doctrine\Common\Cache\FilesystemCache
    oro_security.acl.annotation_reader.class:                 Oro\Bundle\SecurityBundle\Annotation\Loader\AclAnnotationLoader
    oro_security.acl.config_reader.class:                     Oro\Bundle\SecurityBundle\Annotation\Loader\AclYamlConfigLoader

    oro_security.acl.pointcut.class:                          Oro\Bundle\SecurityBundle\Acl\Interceptor\AclPointcut
    oro_security.acl.interceptor.class:                       Oro\Bundle\SecurityBundle\Acl\Interceptor\AclInterceptor

    oro_user.acl.manager.api.class:     Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_user.acl.twig.class:            Oro\Bundle\UserBundle\Twig\OroUserExtension

services:
    oro_security.acl.manager:
        class: %oro_security.acl.manager.class%
        scope: prototype
        arguments:
            - @oro_security.acl.object_identity_factory
            - @oro_security.acl.extension_selector
            - @?security.acl.dbal.provider
            - @oro_security.acl.ace_provider
            - %oro_security.acl.privilege_repository.class%

    security.acl.cache.doctrine.cache_impl:
        public: false
        class: %oro_security.acl.cache.class%
        arguments:
            - %kernel.cache_dir%/oro_security_acl

    oro_security.acl.ace_provider:
        public: false
        class: %oro_security.acl.ace_provider.class%

    oro_security.acl.extension_selector:
        public: false
        class: %oro_security.acl.extension_selector.class%
        arguments:
            - @oro_security.acl.object_id_accessor

    oro_security.acl.extension.entity:
        public: false
        class: %oro_security.acl.extension.entity.class%
        arguments:
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.orm.entity_class_resolver
            - @oro_security.entity_security_metadata_provider
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.decision_maker
        tags:
            - { name: oro_security.acl.extension, priority: 20 }

    oro_security.acl.extension.action:
        public: false
        class: %oro_security.acl.extension.action.class%
        arguments:
            - @oro_security.action_metadata_provider
        tags:
            - { name: oro_security.acl.extension, priority: 10 }

    oro_security.acl.provider:
        public: false
        class: %oro_security.acl.provider.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.permission_granting_strategy:
        public: false
        class: %oro_security.acl.permission_granting_strategy.class%
        calls:
             - [setAuditLogger, ["@?security.acl.audit_logger"]]

    oro_security.acl.permission_map:
        public: false
        class: %oro_security.acl.permission_map.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_factory:
        class: %oro_security.acl.object_identity_factory.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_retrieval_strategy:
        public: false
        class: %oro_security.acl.object_identity_retrieval_strategy.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.object_id_accessor:
        public: false
        class: %oro_security.acl.object_id_accessor.class%

    oro_security.owner.tree:
        public: false
        class: %oro_security.owner.tree.class%

    oro_security.owner.decision_maker:
        public: false
        class: %oro_security.owner.decision_maker.class%
        arguments:
            - @oro_security.owner.tree
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.owner.entity_owner_accessor
            - @oro_entity.owner.ownership_metadata_provider

    oro_security.orm.ownership_sql_filter_builder:
        public: false
        class: %oro_security.orm.ownership_sql_filter_builder.class%
        arguments:
            - @oro_entity_config.link.security_context
            - @oro_security.acl.object_id_accessor
            - @oro_security.entity_security_metadata_provider
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.tree
            - @?security.acl.voter.basic_permissions

    oro_security.orm.ownership_sql_filter:
        public: false
        class: %oro_security.orm.ownership_sql_filter.class%
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [setBuilder, ["@oro_security.orm.ownership_sql_filter_builder"]]
        tags:
            - { name: oro_entity.orm.sql_filter, filter_name: ownershipFilter, enabled: true }
            - { name: kernel.event_listener, priority: -255, event: kernel.request, method: setUserParameter }
    
    oro_security.form.type.collection_type:
        class: %oro_security.type.oro_acl_collection.class%
        tags:
            - { name: form.type, alias: oro_acl_collection }

    oro_security.form.type.ownership_type:
        class: %oro_security.type.oro_acl_entity_row.class%
        tags:
            - { name: form.type, alias: oro_acl_entity_row }

    oro_security.form.type.object_name_type:
        class: %oro_security.type.oro_acl_object_name.class%
        tags:
            - { name: form.type, alias: oro_acl_object_name }

    oro_security.form.type.object_label_type:
        class: %oro_security.type.oro_acl_label.class%
        tags:
            - { name: form.type, alias: oro_acl_label }
            
    oro_security.entity_security_metadata_provider:
        public: false
        class: %oro_security.entity_security_metadata_provider.class%
        arguments:
            - @oro_entity_config.provider.security
            - @oro_entity_config.provider.entity
            - @oro_security.entity_security_metadata_provider.cache

    oro_security.entity_security_metadata_provider.cache:
        public: false
        class: %oro_security.entity_security_metadata_provider.cache.class%
        arguments:
            - %kernel.cache_dir%/oro_security_entity_metadata

    oro_security.action_metadata_provider:
        public: false
        class: %oro_security.action_metadata_provider.class%

    oro_security.acl.annotation_provider.cache:
        public: false
        class: %oro_security.acl.annotation_provider.cache.class%
        arguments:
            - %kernel.cache_dir%/oro_security_acl_annotations

    oro_security.acl.annotation_loader:
        public: false
        class:                        %oro_security.acl.annotation_reader.class%
        arguments:                    ["@kernel", "@annotation_reader", "@oro_security.acl.extension_selector"]
        tags:
            -  { name: oro_security.acl.metadata_loader }

    oro_security.acl.config_loader:
        public: false
        class:                        %oro_security.acl.config_reader.class%
        arguments:                    ["@kernel", "@oro_security.acl.extension_selector"]
        tags:
            -  { name: oro_security.acl.metadata_loader }

    oro_security.acl.annotation_provider:
        class:                        %oro_security.acl.annotation_provider.class%
        arguments:
          - ~
          - "@oro_security.acl.annotation_provider.cache"

    oro_security.acl.pointcut:
        public: false
        class: %oro_security.acl.pointcut.class%
        arguments:
            - @oro_security.acl.annotation_provider
        tags:
            - { name: jms_aop.pointcut, interceptor: oro_security.acl.interceptor }

    oro_security.acl.interceptor:
        public: false
        scope: request
        class: %oro_security.acl.interceptor.class%
        arguments:
          - @logger
          - @service_container
          - @oro_security.acl.annotation_provider
          - @oro_security.acl.object_identity_factory
          - @request

 #   oro_user.acl_manager.api:
 #       class:                        %oro_user.acl.manager.api.class%
 #       arguments:                    [%oro_user.acl.entity.class%, @doctrine.orm.entity_manager]
