parameters:
    oro_security.security_facade.class:                        Oro\Bundle\SecurityBundle\SecurityFacade
    oro_security.acl.manager.class:                            Oro\Bundle\SecurityBundle\Acl\Persistence\AclManager
    oro_security.acl.sid_manager.class:                        Oro\Bundle\SecurityBundle\Acl\Persistence\AclSidManager
    oro_security.acl.cache.class:                              Oro\Bundle\SecurityBundle\Acl\Cache\FilesystemCache
    oro_security.acl.ace_provider.class:                       Oro\Bundle\SecurityBundle\Acl\Persistence\AceManipulationHelper
    oro_security.acl.privilege_repository.class:               Oro\Bundle\SecurityBundle\Acl\Persistence\AclPrivilegeRepository
    oro_security.acl.extension_selector.class:                 Oro\Bundle\SecurityBundle\Acl\Extension\AclExtensionSelector
    oro_security.acl.extension.entity.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\EntityAclExtension
    oro_security.acl.extension.action.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\ActionAclExtension
    oro_security.acl.voter.class:                              Oro\Bundle\SecurityBundle\Acl\Voter\AclVoter
    oro_security.acl.provider.class:                           Oro\Bundle\SecurityBundle\Acl\Domain\RootBasedAclProvider
    oro_security.acl.dbal.provider.class:                      Oro\Bundle\SecurityBundle\Acl\Dbal\MutableAclProvider
    oro_security.acl.permission_granting_strategy.class:       Oro\Bundle\SecurityBundle\Acl\Domain\PermissionGrantingStrategy
    oro_security.acl.permission_map.class:                     Oro\Bundle\SecurityBundle\Acl\Permission\PermissionMap
    oro_security.acl.object_identity_factory.class:            Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityFactory
    oro_security.acl.object_identity_retrieval_strategy.class: Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityRetrievalStrategy
    oro_security.acl.object_id_accessor.class:                 Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdAccessor

    oro_security.owner.tree.class:                             Oro\Bundle\SecurityBundle\Owner\OwnerTree
    oro_security.owner.decision_maker.class:                   Oro\Bundle\SecurityBundle\Owner\EntityOwnershipDecisionMaker
    oro_security.orm.ownership_sql_filter.class:               Oro\Bundle\SecurityBundle\ORM\SqlFilter\OwnershipFilter
    oro_security.orm.ownership_sql_filter_builder.class:       Oro\Bundle\SecurityBundle\ORM\SqlFilter\OwnershipFilterBuilder

    oro_security.type.oro_acl_entity_row.class:                Oro\Bundle\SecurityBundle\Form\Type\EntityRowType
    oro_security.type.oro_acl_collection.class:                Oro\Bundle\SecurityBundle\Form\Type\CollectionType
    oro_security.type.oro_acl_object_name.class:               Oro\Bundle\SecurityBundle\Form\Type\ObjectNameType
    oro_security.type.oro_acl_label.class:                     Oro\Bundle\SecurityBundle\Form\Type\ObjectLabelType

    oro_security.entity_security_metadata_provider.class:      Oro\Bundle\SecurityBundle\Metadata\EntitySecurityMetadataProvider
    oro_security.action_metadata_provider.class:               Oro\Bundle\SecurityBundle\Metadata\ActionMetadataProvider

    oro_security.acl.annotation_provider.class:                Oro\Bundle\SecurityBundle\Metadata\AclAnnotationProvider
    oro_security.acl.annotation_provider.cache.class:          Doctrine\Common\Cache\FilesystemCache
    oro_security.acl.annotation_loader.class:                  Oro\Bundle\SecurityBundle\Annotation\Loader\AclAnnotationLoader
    oro_security.acl.yaml_config_loader.class:                 Oro\Bundle\SecurityBundle\Annotation\Loader\AclYamlConfigLoader

    oro_security.entity_security_config_subscriber.class:      Oro\Bundle\SecurityBundle\EventListener\EntitySecurityMetadataConfigSubscriber
    oro_security.acl.annotation_provider.cache.warmer.class:   Oro\Bundle\SecurityBundle\Cache\AclAnnotationCacheWarmer
    oro_security.acl.annotation_provider.cache.clearer.class:  Oro\Bundle\SecurityBundle\Cache\AclAnnotationCacheClearer
    oro_security.action_metadata_provider.cache.warmer.class:  Oro\Bundle\SecurityBundle\Cache\ActionMetadataCacheWarmer
    oro_security.action_metadata_provider.cache.clearer.class: Oro\Bundle\SecurityBundle\Cache\ActionMetadataCacheClearer
    oro_security.entity_security_metadata_provider.cache.warmer.class:  Oro\Bundle\SecurityBundle\Cache\EntitySecurityMetadataCacheWarmer
    oro_security.entity_security_metadata_provider.cache.clearer.class: Oro\Bundle\SecurityBundle\Cache\EntitySecurityMetadataCacheClearer

    oro_security.listener.config_subscriber.class:             Oro\Bundle\SecurityBundle\EventListener\ConfigSubscriber
    oro_security.listener.controller.class:                    Oro\Bundle\SecurityBundle\EventListener\ControllerListener

    oro_user.acl.manager.api.class:     Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_security.twig.security_extension:                      Oro\Bundle\SecurityBundle\Twig\OroSecurityExtension

    oro_security.encoder.mcrypt.class:                         Oro\Bundle\SecurityBundle\Encoder\Mcrypt

services:
    oro_security.security_facade:
        class: %oro_security.security_facade.class%
        arguments:
            - @security.context
            - @oro_security.acl.annotation_provider
            - @oro_security.acl.object_identity_factory
            - @logger
        tags:
            - { name: monolog.logger, channel: security }

    oro_security.acl.manager:
        class: %oro_security.acl.manager.class%
        scope: prototype
        arguments:
            - @oro_security.acl.object_identity_factory
            - @oro_security.acl.extension_selector
            - @?security.acl.dbal.provider
            - @oro_security.acl.ace_provider
            - %oro_security.acl.privilege_repository.class%

    oro_security.acl.sid_manager:
        class: %oro_security.acl.sid_manager.class%
        arguments:
            - @?security.acl.dbal.provider

    oro_security.link.sid_manager:
        tags:
            - { name: oro_service_link,  service: oro_security.acl.sid_manager }

    security.acl.cache.doctrine.cache_impl:
        public: false
        class: %oro_security.acl.cache.class%
        arguments:
            - %kernel.cache_dir%/oro_acl

    oro_security.acl.ace_provider:
        public: false
        class: %oro_security.acl.ace_provider.class%

    oro_security.acl.extension_selector:
        public: false
        class: %oro_security.acl.extension_selector.class%
        arguments:
            - @oro_security.acl.object_id_accessor

    oro_security.acl.extension.entity:
        public: false
        class: %oro_security.acl.extension.entity.class%
        arguments:
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.orm.entity_class_resolver
            - @oro_security.entity_security_metadata_provider
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.decision_maker
        tags:
            - { name: oro_security.acl.extension, priority: 20 }

    oro_security.acl.extension.action:
        public: false
        class: %oro_security.acl.extension.action.class%
        arguments:
            - @oro_security.action_metadata_provider
        tags:
            - { name: oro_security.acl.extension, priority: 10 }

    oro_security.acl.provider:
        public: false
        class: %oro_security.acl.provider.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.voter_link:
        tags:
            - { name: oro_service_link,  service: ?security.acl.voter.basic_permissions }

    oro_security.acl.permission_granting_strategy:
        public: false
        class: %oro_security.acl.permission_granting_strategy.class%
        calls:
             - [setAuditLogger, [@?security.acl.audit_logger]]

    oro_security.acl.permission_map:
        public: false
        class: %oro_security.acl.permission_map.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_factory:
        class: %oro_security.acl.object_identity_factory.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_retrieval_strategy:
        public: false
        class: %oro_security.acl.object_identity_retrieval_strategy.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.object_id_accessor:
        public: false
        class: %oro_security.acl.object_id_accessor.class%

    oro_security.owner.tree:
        public: false
        class: %oro_security.owner.tree.class%

    oro_security.owner.decision_maker:
        public: false
        class: %oro_security.owner.decision_maker.class%
        arguments:
            - @oro_security.owner.tree
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.owner.entity_owner_accessor
            - @oro_entity.owner.ownership_metadata_provider

    oro_security.orm.ownership_sql_filter_builder:
        public: false
        class: %oro_security.orm.ownership_sql_filter_builder.class%
        arguments:
            - @oro_entity_config.link.security_context
            - @oro_security.acl.object_id_accessor
            - @oro_security.entity_security_metadata_provider
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.tree
            - @?security.acl.voter.basic_permissions

#    oro_security.orm.ownership_sql_filter:
#        public: false
#        class: %oro_security.orm.ownership_sql_filter.class%
#        arguments:
#            - @doctrine.orm.entity_manager
#        calls:
#            - [setBuilder, [@oro_security.orm.ownership_sql_filter_builder]]
#        tags:
#            - { name: oro_entity.orm.sql_filter, filter_name: ownershipFilter, enabled: true }
#            - { name: kernel.event_listener, priority: -255, event: kernel.request, method: setUserParameter }

    oro_security.form.type.collection_type:
        class: %oro_security.type.oro_acl_collection.class%
        tags:
            - { name: form.type, alias: oro_acl_collection }

    oro_security.form.type.ownership_type:
        class: %oro_security.type.oro_acl_entity_row.class%
        tags:
            - { name: form.type, alias: oro_acl_entity_row }

    oro_security.form.type.object_name_type:
        class: %oro_security.type.oro_acl_object_name.class%
        tags:
            - { name: form.type, alias: oro_acl_object_name }

    oro_security.form.type.object_label_type:
        class: %oro_security.type.oro_acl_label.class%
        tags:
            - { name: form.type, alias: oro_acl_label }

    oro_security.entity_security_metadata_provider:
        public: false
        class: %oro_security.entity_security_metadata_provider.class%
        arguments:
            - @oro_entity_config.provider.security
            - @oro_entity_config.provider.entity
            - @oro_security.entity_security_metadata_provider.cache

    oro_security.entity_security_metadata_provider.cache:
        public: false
        parent: oro_entity.owner.ownership_metadata_provider.cache

    oro_security.action_metadata_provider:
        public: false
        class: %oro_security.action_metadata_provider.class%
        arguments:
            - @oro_security.acl.annotation_provider
            - @oro_security.action_metadata_provider.cache

    oro_security.action_metadata_provider.cache:
        public: false
        parent: oro_security.acl.annotation_provider.cache

    oro_security.acl.annotation_provider:
        class: %oro_security.acl.annotation_provider.class%
        arguments:
          - @oro_security.acl.annotation_provider.cache

    oro_security.acl.annotation_provider.cache:
        public: false
        class: %oro_security.acl.annotation_provider.cache.class%
        arguments:
            - %kernel.cache_dir%/oro_acl_annotations

    oro_security.acl.annotation_loader:
        public: false
        class: %oro_security.acl.annotation_loader.class%
        arguments:
            - %kernel.bundles%
            - ["Controller"]
            - @annotation_reader
        tags:
            - { name: oro_security.acl.config_loader }

    oro_security.acl.yaml_config_loader:
        public: false
        class: %oro_security.acl.yaml_config_loader.class%
        arguments:
            - %kernel.bundles%
        tags:
            - { name: oro_security.acl.config_loader }

    oro_security.entity_security_config_subscriber:
        class: %oro_security.entity_security_config_subscriber.class%
        arguments:
            - @oro_security.entity_security_metadata_provider
        tags:
            - { name: kernel.event_subscriber }

    oro_security.acl.annotation_provider.cache.warmer:
        public: false
        class: %oro_security.acl.annotation_provider.cache.warmer.class%
        arguments:
            - @oro_security.acl.annotation_provider
        tags:
            - { name: kernel.cache_warmer}

    oro_security.acl.annotation_provider.cache.clearer:
        public: false
        class: %oro_security.acl.annotation_provider.cache.clearer.class%
        arguments:
            - @oro_security.acl.annotation_provider
        tags:
            - { name: kernel.cache_clearer }

    oro_security.action_metadata_provider.cache.warmer:
        public: false
        class: %oro_security.action_metadata_provider.cache.warmer.class%
        arguments:
            - @oro_security.action_metadata_provider
        tags:
            - { name: kernel.cache_warmer}

    oro_security.action_metadata_provider.cache.clearer:
        public: false
        class: %oro_security.action_metadata_provider.cache.clearer.class%
        arguments:
            - @oro_security.action_metadata_provider
        tags:
            - { name: kernel.cache_clearer }

    oro_security.entity_security_metadata_provider.cache.warmer:
        public: false
        class: %oro_security.entity_security_metadata_provider.cache.warmer.class%
        arguments:
            - @oro_security.entity_security_metadata_provider
        tags:
            - { name: kernel.cache_warmer}

    oro_security.entity_security_metadata_provider.cache.clearer:
        public: false
        class: %oro_security.entity_security_metadata_provider.cache.clearer.class%
        arguments:
            - @oro_security.entity_security_metadata_provider
        tags:
            - { name: kernel.cache_clearer }

    oro_security.listener.config_subscriber:
        class: %oro_security.listener.config_subscriber.class%
        tags:
            - { name: kernel.event_subscriber}

    oro_security.listener.controller:
        class: %oro_security.listener.controller.class%
        arguments:
            - @oro_security.security_facade
            - @logger
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 255 }
            - { name: monolog.logger, channel: security }

    oro_security.twig.security_extension:
        class: %oro_security.twig.security_extension%
        arguments:
            - @oro_security.security_facade
        tags:
            - { name: twig.extension }

    oro_security.encoder.mcrypt:
        class: %oro_security.encoder.mcrypt.class%
        arguments: [ %kernel.secret% ]
