parameters:
    # replace the default ACL provider with an extended version of the provider
    security.acl.dbal.provider.class:                          Oro\Bundle\SecurityBundle\Acl\Dbal\MutableAclProvider

    oro_security.acl.manager.class:                            Oro\Bundle\SecurityBundle\Acl\Persistence\AclManager
    oro_security.acl.ace_provider.class:                       Oro\Bundle\SecurityBundle\Acl\Persistence\AceManipulationHelper
    oro_security.acl.privilege_repository.class:               Oro\Bundle\SecurityBundle\Acl\Persistence\AclPrivilegeRepository
    oro_security.acl.extension_selector.class:                 Oro\Bundle\SecurityBundle\Acl\Extension\AclExtensionSelector
    oro_security.acl.extension.entity.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\EntityAclExtension
    oro_security.acl.extension.action.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\ActionAclExtension
    oro_security.acl.voter.class:                              Oro\Bundle\SecurityBundle\Acl\Voter\AclVoter
    oro_security.acl.provider.class:                           Oro\Bundle\SecurityBundle\Acl\Domain\RootBasedAclProvider
    oro_security.acl.permission_granting_strategy.class:       Oro\Bundle\SecurityBundle\Acl\Domain\PermissionGrantingStrategy
    oro_security.acl.permission_map.class:                     Oro\Bundle\SecurityBundle\Acl\Permission\PermissionMap
    oro_security.acl.object_identity_factory.class:            Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityFactory
    oro_security.acl.object_identity_retrieval_strategy.class: Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityRetrievalStrategy
    oro_security.acl.object_id_accessor.class:                 Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdAccessor

    oro_security.owner.tree.class:                             Oro\Bundle\SecurityBundle\Owner\OwnerTree
    oro_security.owner.decision_maker.class:                   Oro\Bundle\SecurityBundle\Owner\EntityOwnershipDecisionMaker
    oro_security.orm.ownership_sql_filter.class:               Oro\Bundle\SecurityBundle\ORM\SqlFilter\OwnershipFilter
    oro_security.orm.ownership_sql_filter_builder.class:       Oro\Bundle\SecurityBundle\ORM\OwnershipSqlFilterBuilder

services:
    oro_security.acl.manager:
        class: %oro_security.acl.manager.class%
        scope: prototype
        arguments:
            - @oro_security.acl.object_identity_factory
            - @oro_security.acl.extension_selector
            - @?security.acl.dbal.provider
            - @oro_security.acl.ace_provider
            - %oro_security.acl.privilege_repository.class%

    oro_security.acl.ace_provider:
        public: false
        class: %oro_security.acl.ace_provider.class%

    oro_security.acl.extension_selector:
        public: false
        class: %oro_security.acl.extension_selector.class%
        arguments:
            - @oro_security.acl.object_id_accessor

    oro_security.acl.extension.entity:
        public: false
        class: %oro_security.acl.extension.entity.class%
        arguments:
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.orm.entity_class_resolver
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.decision_maker
        tags:
            - { name: oro_security.acl.extension, priority: 20 }

    oro_security.acl.extension.action:
        public: false
        class: %oro_security.acl.extension.action.class%
        tags:
            - { name: oro_security.acl.extension, priority: 10 }

    oro_security.acl.provider:
        public: false
        class: %oro_security.acl.provider.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.permission_granting_strategy:
        public: false
        class: %oro_security.acl.permission_granting_strategy.class%
        calls:
             - [setAuditLogger, ["@?security.acl.audit_logger"]]

    oro_security.acl.permission_map:
        public: false
        class: %oro_security.acl.permission_map.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_factory:
        class: %oro_security.acl.object_identity_factory.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_retrieval_strategy:
        public: false
        class: %oro_security.acl.object_identity_retrieval_strategy.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.object_id_accessor:
        public: false
        class: %oro_security.acl.object_id_accessor.class%

    oro_security.owner.tree:
        public: false
        class: %oro_security.owner.tree.class%

    oro_security.owner.decision_maker:
        public: false
        class: %oro_security.owner.decision_maker.class%
        arguments:
            - @oro_security.owner.tree
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.owner.entity_owner_accessor
            - @oro_entity.owner.ownership_metadata_provider

    oro_security.orm.ownership_sql_filter_builder:
        public: true
        class: %oro_security.orm.ownership_sql_filter_builder.class%
        arguments:
            - @oro_entity_config.link.security_context
            - @oro_security.acl.object_id_accessor
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.tree
            - @?security.acl.voter.basic_permissions

    oro_security.orm.ownership_sql_filter:
        class: %oro_security.orm.ownership_sql_filter.class%
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [setBuilder, ["@oro_security.orm.ownership_sql_filter_builder"]]
        tags:
            - { name: oro_entity.orm.sql_filter, filter_name: ownershipFilter, enabled: true }
            - { name: kernel.event_listener, priority: -255, event: kernel.request, method: setUserParameter }
