parameters:
    oro_security.acl.extension_selector.class:                 Oro\Bundle\SecurityBundle\Acl\Extension\AclExtensionSelector
    oro_security.acl.extension.entity.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\EntityAclExtension
    oro_security.acl.extension.action.class:                   Oro\Bundle\SecurityBundle\Acl\Extension\ActionAclExtension
    oro_security.acl.voter.class:                              Oro\Bundle\SecurityBundle\Acl\Voter\AclVoter
    oro_security.acl.provider.class:                           Oro\Bundle\SecurityBundle\Acl\Domain\RootBasedAclProvider
    oro_security.acl.permission_granting_strategy.class:       Oro\Bundle\SecurityBundle\Acl\Domain\PermissionGrantingStrategy
    oro_security.acl.permission_map.class:                     Oro\Bundle\SecurityBundle\Acl\Permission\PermissionMap
    oro_security.acl.object_identity_factory.class:            Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityFactory
    oro_security.acl.object_identity_retrieval_strategy.class: Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityRetrievalStrategy
    oro_security.acl.object_id_accessor.class:                 Oro\Bundle\SecurityBundle\Acl\Domain\ObjectIdAccessor

    oro_security.owner.tree.class:                             Oro\Bundle\SecurityBundle\Owner\OwnerTree
    oro_security.owner.decision_maker.class:                   Oro\Bundle\SecurityBundle\Owner\EntityOwnershipDecisionMaker

    oro_security.type.oro_acl_entity_row.class:               Oro\Bundle\SecurityBundle\Form\Type\EntityRowType
    oro_security.type.oro_acl_collection.class:               Oro\Bundle\SecurityBundle\Form\Type\CollectionType
    oro_security.type.oro_acl_object_name.class:              Oro\Bundle\SecurityBundle\Form\Type\ObjectNameType
    oro_security.type.oro_acl_label.class:                    Oro\Bundle\SecurityBundle\Form\Type\ObjectLabelType

services:
    oro_security.acl.extension_selector:
        public: false
        class: %oro_security.acl.extension_selector.class%
        arguments:
            - @oro_security.acl.object_id_accessor

    oro_security.acl.extension.entity:
        public: false
        class: %oro_security.acl.extension.entity.class%
        arguments:
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.orm.entity_class_resolver
            - @oro_entity.owner.ownership_metadata_provider
            - @oro_security.owner.decision_maker
        tags:
            - { name: oro_security.acl.extension, priority: 20 }

    oro_security.acl.extension.action:
        public: false
        class: %oro_security.acl.extension.action.class%
        tags:
            - { name: oro_security.acl.extension, priority: 10 }

    oro_security.acl.provider:
        public: false
        class: %oro_security.acl.provider.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.permission_granting_strategy:
        public: false
        class: %oro_security.acl.permission_granting_strategy.class%
        calls:
             - [setAuditLogger, ["@?security.acl.audit_logger"]]

    oro_security.acl.permission_map:
        public: false
        class: %oro_security.acl.permission_map.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_factory:
        class: %oro_security.acl.object_identity_factory.class%
        arguments:
            - @oro_security.acl.extension_selector

    oro_security.acl.object_identity_retrieval_strategy:
        public: false
        class: %oro_security.acl.object_identity_retrieval_strategy.class%
        arguments:
            - @oro_security.acl.object_identity_factory

    oro_security.acl.object_id_accessor:
        public: false
        class: %oro_security.acl.object_id_accessor.class%

    oro_security.owner.tree:
        public: false
        class: %oro_security.owner.tree.class%

    oro_security.owner.decision_maker:
        public: false
        class: %oro_security.owner.decision_maker.class%
        arguments:
            - @oro_security.owner.tree
            - @oro_entity.orm.entity_class_accessor
            - @oro_security.acl.object_id_accessor
            - @oro_entity.orm.entity_owner_accessor
            - @oro_entity.owner.ownership_metadata_provider

    oro_security.form.type.collection_type:
        class:                        %oro_security.type.oro_acl_collection.class%
        tags:
            - { name: form.type, alias: oro_acl_collection }

    oro_security.form.type.ownership_type:
        class:                        %oro_security.type.oro_acl_entity_row.class%
        tags:
            - { name: form.type, alias: oro_acl_entity_row }

    oro_security.form.type.object_name_type:
        class:                        %oro_security.type.oro_acl_object_name.class%
        tags:
            - { name: form.type, alias: oro_acl_object_name }

    oro_security.form.type.object_label_type:
        class:                        %oro_security.type.oro_acl_label.class%
        tags:
            - { name: form.type, alias: oro_acl_label }